# Generated by Django 3.0.3 on 2020-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('nid_number', models.CharField(max_length=12)),
            ],
        ),
    ]
